version: '3'

services: 
    redis:
        image: redis
        command: redis-server --require-pass yourpass
        networks: 
            - pemro_networks

    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            NODE_ENV: production
            DATABASE_HOST: mysql
            DATABASE_NAME: db_name
            DATABASE_USERNAME: db_user
            DATABASE_PASSWORD: db_pass
            BOT_NAME: "Bot UNEJ"
            BOT_USERNAME: bot_user
            BOT_TOKEN: token
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: yourpass
            WEBHOOK_DOMAIN: "https://yourdomain.com"
            WEBHOOK_PORT: 3000
        networks: 
            - pemro_networks

networks: 
    pemro_networks:
        external: true